/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ticket;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Alice
 */
public class TicketMachine extends javax.swing.JFrame {

    /**
     * Creates new form TicketMachine
     */
    public TicketMachine() {
        initComponents();
    }
    //valor inicial do saldo
    private int saldo;

    public void setSaldo(int newSaldo) {
        saldo = newSaldo;
    }

    public int getSaldo() {
        return saldo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSALDO = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelVALOR = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonEmitir = new javax.swing.JButton();
        jButtonTroco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSALDO.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabelSALDO.setText("Saldo Total");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jLabelVALOR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVALOR.setText("Valor");

        jLabelSaldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSaldo.setText("0");

        jButtonAdd.setText("Inserir");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEmitir.setText("Emitir");
        jButtonEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmitirActionPerformed(evt);
            }
        });

        jButtonTroco.setText("Troco");
        jButtonTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrocoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonEmitir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTroco)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelVALOR)
                        .addGap(16, 16, 16)
                        .addComponent(jTextFieldValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSALDO)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSaldo)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelSALDO)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSaldo)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVALOR)
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTroco)
                    .addComponent(jButtonEmitir))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        if (jTextFieldValor.getText().equals("") || jTextFieldValor.getText() == null) {
            JOptionPane.showMessageDialog(null, "Por favor insira uma Nota/Moeda para realizar a operação");
        } else {
            try {
                int valorInserir = Integer.parseInt(jTextFieldValor.getText());
                if (valorInserir < 0) {
                    JOptionPane.showMessageDialog(null, "Nota/Moeda não aceita.");;
                } else {
                    JOptionPane pane = new JOptionPane("Por favor aguarde um instante...");
                    final JDialog dialog = pane.createDialog(null, "Dispose");
                    Timer timer = new Timer(3000, new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                            dialog.dispose();
                        }
                    });
                    timer.setRepeats(false);
                    timer.start();
                    dialog.show();
                    timer.stop();

                    //TESTE: O software recebe valores negativos

                    int aux = Integer.parseInt(jLabelSaldo.getText());
                    jLabelSaldo.setText(Integer.toString(aux + valorInserir));
                    jTextFieldValor.setText("");
                    JOptionPane.showMessageDialog(null, "Nota/Moeda aceita com sucesso!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nota/Moeda não aceita.");
            }

        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrocoActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(jLabelSaldo.getText()) > 0) {
            JOptionPane.showMessageDialog(null, "Voce resgatou R$ "+jLabelSaldo.getText()+",00");
            jLabelSaldo.setText(Integer.toString(0, 00));
        } else {
            JOptionPane.showMessageDialog(this, "Sem Saldo", "Voce esta sem saldo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTrocoActionPerformed

    private void jButtonEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmitirActionPerformed
        int VALORPASSAGEM = 3;
        int qtdTickets = 0;

        if (Integer.parseInt(jLabelSaldo.getText()) < 3) {
            JOptionPane.showMessageDialog(null, "Voce deve colocar mais dinheiro, o Ticket custa R$ " + Integer.toString(VALORPASSAGEM) + ",00 e voce possui: R$ " + Integer.parseInt(jLabelSaldo.getText()) + ",00");
        } else {
            JOptionPane pane = new JOptionPane("Valor do ticket: " + VALORPASSAGEM + ",00");
            final JDialog dialog = pane.createDialog(null, "Preco Ticket");
            Timer timer = new Timer(3000, new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    dialog.dispose();
                }
            });
            timer.setRepeats(false);
            timer.start();
            dialog.show();
            timer.stop();
            
            int valorLabel = Integer.parseInt(jLabelSaldo.getText());
            int resto = valorLabel % 3;

            qtdTickets = (valorLabel - resto) / 3;
            JOptionPane.showMessageDialog(null, "Emitiu-se " + qtdTickets + (qtdTickets > 1 ? " Tickets" : " Ticket"));
            jLabelSaldo.setText(Integer.toString(resto));
        }
    }//GEN-LAST:event_jButtonEmitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketMachine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEmitir;
    private javax.swing.JButton jButtonTroco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSALDO;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelVALOR;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
